if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/docs/architecture.md" architecture_documentation)
foreach(required_owner IN ITEMS
        "ImageInformation::Dialog"
        "Settings::Editor"
        "ProcessTestAdapter"
        "ViewerWindowTestControl")
    if(NOT architecture_documentation MATCHES "${required_owner}")
        message(FATAL_ERROR "Architecture documentation omits final owner: ${required_owner}")
    endif()
endforeach()

file(READ "${SOURCE_DIR}/src/viewer_window_test_control.h" test_control)
if(test_control MATCHES "QByteArray")
    message(FATAL_ERROR "Window test seam exposes protocol-serialized values")
endif()
if(test_control MATCHES "QWidget[ \t]*\\*|QAction[ \t]*\\*|QAbstractButton[ \t]*\\*")
    message(FATAL_ERROR "Window test seam exposes widget or control pointers")
endif()
if(test_control MATCHES "FocusErrorDetails|FocusLargeImageSkip|ToggleErrorDetails|ApproveLargeImage|RejectLargeImage")
    message(FATAL_ERROR "Window test seam names presentation widgets instead of semantic action roles")
endif()

function(classify_window_test_interface contents output_variable)
    set(violation "")
    if(contents MATCHES
            "(QByteArray|QString|std::string)[ \t\r\n]+[A-Za-z_][A-Za-z0-9_]*[ \t\r\n]*\\(")
        set(violation "serialized scalar result")
    elseif(contents MATCHES
            "(void|bool|int|QByteArray|QString)[ \t\r\n]+[A-Za-z_][A-Za-z0-9_]*(Button|Widget|Control|Details)[A-Za-z0-9_]*[ \t\r\n]*\\(")
        set(violation "UI-representation control")
    endif()
    set(${output_variable} "${violation}" PARENT_SCOPE)
endfunction()

classify_window_test_interface("${test_control}" test_interface_violation)
if(test_interface_violation)
    message(FATAL_ERROR "Window test seam exposes ${test_interface_violation}")
endif()
classify_window_test_interface("QString buildPacket() const;" mutation_violation)
if(NOT mutation_violation STREQUAL "serialized scalar result")
    message(FATAL_ERROR "Architecture guard accepts renamed serialized output at the window seam")
endif()
classify_window_test_interface("void selectRetryButton();" mutation_violation)
if(NOT mutation_violation STREQUAL "UI-representation control")
    message(FATAL_ERROR "Architecture guard accepts renamed UI-specific control at the window seam")
endif()

file(READ "${SOURCE_DIR}/src/settings_editor.h" settings_editor)
if(settings_editor MATCHES "parseTest|describeTest|dialogStructure|dialogFocusOrder")
    message(FATAL_ERROR "Settings owns test protocol parsing or serialization")
endif()
if(settings_editor MATCHES "DialogGroup|settingsFileName|QStringList|[ \t]groups;|[ \t]buttons;|[ \t]focusOrder;")
    message(FATAL_ERROR "Settings test seam mirrors protocol fields or the dialog control tree")
endif()

file(READ "${SOURCE_DIR}/src/process_test_adapter.cpp" adapter)
foreach(protocol_owner IN ITEMS "startsWith" "fprintf" "parseSettings" "describeSettings"
                                "describePresentation" "describeActions")
    if(NOT adapter MATCHES "${protocol_owner}")
        message(FATAL_ERROR "Process adapter does not own protocol operation: ${protocol_owner}")
    endif()
endforeach()

function(classify_forbidden_test_contract contents output_variable)
    set(violation "")
    if(contents MATCHES
            "QByteArray[ \t\r\n]+[A-Za-z_][A-Za-z0-9_]*(describe|Describe|serialize|Serialize|encode|Encode|format|Format|reply|Reply|response|Response)[A-Za-z0-9_]*[ \t\r\n]*\\(")
        set(violation "protocol serialization")
    elseif(contents MATCHES
            "(void|bool|int|QByteArray|QString)[ \t\r\n]+(focus|Focus|toggle|Toggle|click|Click|press|Press)[A-Za-z0-9_]*(Button|Widget|Control|Details)[A-Za-z0-9_]*[ \t\r\n]*\\(")
        set(violation "widget-named test operation")
    elseif(contents MATCHES "fprintf[ \t\r\n]*\\([ \t\r\n]*stdout")
        set(violation "line-protocol output")
    endif()
    set(${output_variable} "${violation}" PARENT_SCOPE)
endfunction()

# Mutation probes keep this contract semantic rather than tied to the names removed by the
# original refactor. Equivalent protocol or widget coupling must also be rejected.
classify_forbidden_test_contract("QByteArray encodeReply() const;" mutation_violation)
if(NOT mutation_violation STREQUAL "protocol serialization")
    message(FATAL_ERROR "Architecture guard accepts renamed protocol serialization")
endif()
classify_forbidden_test_contract("void focusRetryButton();" mutation_violation)
if(NOT mutation_violation STREQUAL "widget-named test operation")
    message(FATAL_ERROR "Architecture guard accepts renamed widget-specific control")
endif()
classify_forbidden_test_contract("fprintf(stdout, \"%s\\n\", reply);" mutation_violation)
if(NOT mutation_violation STREQUAL "line-protocol output")
    message(FATAL_ERROR "Architecture guard accepts process-protocol output outside the adapter")
endif()

file(GLOB production_sources "${SOURCE_DIR}/src/*.cpp" "${SOURCE_DIR}/src/*.h")
foreach(source IN LISTS production_sources)
    if(source MATCHES "process_test_adapter\\.(cpp|h)$")
        continue()
    endif()
    file(READ "${source}" contents)
    classify_forbidden_test_contract("${contents}" contract_violation)
    if(contract_violation)
        message(FATAL_ERROR "Forbidden ${contract_violation} outside process adapter: ${source}")
    endif()
    if(NOT source MATCHES "test_driver_main\\.cpp$" AND contents MATCHES "FLICK_TEST_")
        message(FATAL_ERROR "Deterministic environment parsing outside test-driver wiring: ${source}")
    endif()
endforeach()
